title: Dennis Alves - Blog
email: dennis.alves@live.com
description: "Ideias, tutoriais e algumas coisas mais..."
baseurl: ""
url: "dennis90.github.io"
twitter_username: _dennis90
github_username:  dennis90
permalink: :year/:month/:title

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
